-- Ensures boss spell definitions and passive setup callbacks are ready before
-- any gameplay initializer creates boss units.

OnInit.final("BossAbilities", function(Require)
    Require("AbsoluteHorrorAbilities")
    Require("ArkadenAbilities")
    Require("Azazoth")
    Require("DeathKnightAbilities")
    Require("DemonPrinceAbilities")
    Require("DragoonAbilities")
    Require("EssenceOfDarknessAbilities")
    Require("ForgottenMysticAbilities")
    Require("GoddessesAbilities")
    Require("HateAbilities")
    Require("HellfireMagiAbilities")
    Require("KnowledgeAbilities")
    Require("LastDwarfAbilities")
    Require("LegionAbilities")
    Require("LoveAbilities")
    Require("MinotaurAbilities")
    Require("NagaAbilities")
    Require("OrstedAbilities")
    Require("PerfectBeing")
    Require("SatanAbilities")
    Require("SirenOfTheTidesAbilities")
    Require("SlaughterQueenAbilities")
    Require("Thanatos")
    Require("VengefulPaladinAbilities")
    Require("Xallarath")
end, Debug and Debug.getLine())
