OnInit.global("StatSchema", function(Require)
    Require('ItemSchema')

    -- Priority: 1 - power, 2 - utility, 3 - player only, 4 - hidden.
    STAT_TAG = {
        [ITEM_LEVEL] = { tag = "Level", priority = 1 },
        [ITEM_HEALTH] = { tag = "|cffff0000Health|r", priority = 1, syntax = "health" },
        [ITEM_MANA] = { tag = "|cff6699ffMana|r", priority = 1, syntax = "mana" },
        [ITEM_DAMAGE] = { tag = "|cffff6600Damage|r", priority = 1, syntax = "damage" },
        [ITEM_ARMOR] = { tag = "|cffa4a4feArmor|r", priority = 1, syntax = "armor" },
        [ITEM_STRENGTH] = { tag = "|cffbb0000Strength|r", priority = 1, syntax = "str" },
        [ITEM_AGILITY] = { tag = "|cff008800Agility|r", priority = 1, syntax = "agi" },
        [ITEM_INTELLIGENCE] = { tag = "|cff2255ffIntelligence|r", priority = 1, syntax = "int" },
        [ITEM_REGENERATION] = { tag = "|cffa00070Regeneration|r", priority = 1, syntax = "regen" },
        [ITEM_MANA_REGENERATION] = { tag = "|cff1144ddMana Regen|r", priority = 1, syntax = "manaregen" },
        [ITEM_DAMAGE_RESIST] = { tag = "|cffff8040Damage Resist|r", alternate = "|cffff8040Physical Taken|r", priority = 1, suffix = "%", syntax = "dr" },
        [ITEM_MAGIC_RESIST] = { tag = "|cff8000ffMagic Resist|r", alternate = "|cff8000ffMagical Taken|r", priority = 1, suffix = "%", syntax = "mr" },
        [ITEM_DAMAGE_MULT] = { tag = "|cffff8040Physical Dealt|r", priority = 1, suffix = "%", syntax = "dm" },
        [ITEM_MAGIC_MULT] = { tag = "|cff8000ffMagic Dealt|r", priority = 1, suffix = "%", syntax = "mm" },
        [ITEM_MOVESPEED] = { tag = "|cff888888Movespeed|r", priority = 2, syntax = "ms" },
        [ITEM_EVASION] = { tag = "|cff008080Evasion|r", priority = 2, suffix = "%", syntax = "evasion" },
        [ITEM_SPELLBOOST] = { tag = "|cff80ffffSpellboost|r", priority = 1, suffix = "%", syntax = "spellboost" },
        [ITEM_CRIT_CHANCE] = { tag = "|cffffcc00Critical Chance|r", priority = 1, suffix = "%", syntax = "cc" },
        [ITEM_CRIT_DAMAGE] = { tag = "|cffffcc00Critical Damage|r", priority = 1, suffix = "%", syntax = "cd" },
        [ITEM_CRIT_CHANCE_MULT] = { tag = "|cffffcc00Critical Chance Multiplier|r", priority = 4, suffix = "%", syntax = "cc_percent" },
        [ITEM_CRIT_DAMAGE_MULT] = { tag = "|cffffcc00Critical Damage Multiplier|r", priority = 4, suffix = "%", syntax = "cd_percent" },
        [ITEM_BASE_ATTACK_SPEED] = { tag = "|cff446600Base Attack Speed|r", priority = 1, item_suffix = "%", syntax = "bat" },
        [ITEM_GOLD_GAIN] = { tag = "|cffffff00Gold Find|r", priority = 3, suffix = "%", syntax = "gold" },
        [ITEM_FLAT_HEAL] = { tag = "|rHealth Restored", priority = 4, syntax = "fheal" },
        [ITEM_PERCENT_HEAL] = { tag = "|rPercent Health Restored", priority = 4, syntax = "pheal", suffix = "%" },
        [ITEM_FLAT_MANA] = { tag = "|rMana Restored", priority = 4, syntax = "fmana" },
        [ITEM_PERCENT_MANA] = { tag = "|rPercent Mana Restored", priority = 4, syntax = "pmana", suffix = "%" },
        [ITEM_CHARGES] = { tag = "|rCharges", priority = 4, syntax = "charges" },
        [ITEM_ABILITY] = { priority = 4, syntax = "abil" },
        [ITEM_ABILITY2] = { priority = 4, syntax = "abiltwo" },
        [ITEM_NOCRAFT] = { priority = 4, syntax = "nocraft" },
        [ITEM_TIER] = { priority = 4, syntax = "tier" },
        [ITEM_TYPE] = { priority = 4, syntax = "type" },
        [ITEM_UPGRADE_MAX] = { priority = 4, syntax = "upg" },
        [ITEM_LEVEL_REQUIREMENT] = { priority = 4, syntax = "req" },
        [ITEM_LIMIT] = { priority = 4, syntax = "limit" },
        [ITEM_COST] = { priority = 4, syntax = "cost" },
        [ITEM_DISCOUNT] = { priority = 4, syntax = "discount" },
        [ITEM_STACK] = { priority = 4, syntax = "stack" },
        [ITEM_RARITY] = { priority = 4, syntax = "rarity" },
        [TOTAL_ATTACK_SPEED] = { tag = "|cff446600Total Attack Speed|r", priority = 1 },
        [XP_RATE] = { tag = "|cff808080Experience Rate|r", priority = 3, suffix = "%" },
        [HERO_TIME] = { tag = "|cff808000Hero Time Played|r", priority = 3 },
        [PLAYER_TIME] = { tag = "|cff808000Total Time Played|r", priority = 3 },
    }
end, Debug and Debug.getLine())
